server.port=8080
server.servlet.context-path=/api/v1
spring.application.name=auth-service
frontend.base-url=${FRONTEND_BASE_URL:http://localhost:3001}

server.ssl.enabled=true
server.ssl.key-store=classpath:auth-server.p12
server.ssl.key-store-password=${auth.server.ssl.key-store-password}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1

server.ssl.client-auth=need
server.ssl.trust-store=classpath:auth-truststore.p12
server.ssl.trust-store-password=${auth.server.ssl.trust-store-password}
server.ssl.trust-store-type=PKCS12

spring.config.import=vault://
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=auth-service
spring.cloud.vault.token=${VAULT_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5433/authdb
spring.datasource.username=postgres
spring.datasource.password=${db.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=localhost
spring.data.redis.port=6379
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mail.username}
spring.mail.password=${mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health,prometheus,metrics
management.server.port=9001
management.server.ssl.enabled=false
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
management.metrics.tags.application=${spring.application.name}
management.observations.key-values.application=${spring.application.name}

spring.rabbitmq.host=${rabbitmq.host}
spring.rabbitmq.port=${rabbitmq.port}
spring.rabbitmq.username=${rabbitmq.username}
spring.rabbitmq.password=${rabbitmq.password}

spring.rabbitmq.template.mandatory=true
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
