from app.prompts.explanation_prompts import build_alert_explanation_prompt
from app.schemas import AlertExplanationRequest, InvestigationResponse
from app.services.llm_service import llm_service


class ExplanationService:
    def explain_alert(self, payload: AlertExplanationRequest) -> InvestigationResponse:
        prompt_summary = build_alert_explanation_prompt(payload)
        llm_answer = llm_service.generate(
            system_prompt=(
                "You explain security alerts in grounded terms. "
                "Do not invent evidence, answer the analyst's alert question directly, "
                "keep the explanation tied to the provided alert details, "
                "and answer in the same language as the analyst."
            ),
            user_prompt=(
                f"{prompt_summary}\n\n"
                f"Title: {payload.title}\n"
                f"Severity: {payload.severity}\n"
                f"Rule: {payload.triggeredRule}\n"
                f"Source: {payload.source}\n"
                f"Reason: {payload.reason}\n"
                f"Supporting evidence: {payload.supportingEvidence}\n"
                f"Anomaly contribution: {payload.anomalyContribution}\n"
                f"Related incidents: {payload.relatedIncidents}\n"
                f"Recommendation: {payload.recommendation}\n"
                f"Mode: {payload.mode}\n"
            ),
        )
        if llm_answer:
            answer = llm_answer
            engine = f"llm:{llm_service.provider}"
        elif payload.mode.lower() == "executive":
            answer = (
                f"This alert is {payload.severity.lower()} severity because the system matched rule "
                f"{payload.triggeredRule}, linked it to incident {payload.relatedIncidents or 'N/A'}, "
                f"and observed anomaly contribution {payload.anomalyContribution or 0:.2f}. In short, {payload.reason}"
            )
            engine = f"grounded-fallback ({llm_service.last_error})" if llm_service.last_error else "grounded-fallback"
        else:
            answer = (
                f"The alert '{payload.title}' was generated by the {payload.source} pipeline after rule "
                f"{payload.triggeredRule} matched. Severity is {payload.severity}. Evidence-based reason: "
                f"{payload.reason}. Supporting evidence: {payload.supportingEvidence or 'N/A'}. "
                f"Related incident(s): {payload.relatedIncidents or 'N/A'}. Recommendation: {payload.recommendation or 'N/A'}"
            )
            engine = f"grounded-fallback ({llm_service.last_error})" if llm_service.last_error else "grounded-fallback"

        return InvestigationResponse(
            answer=answer,
            mode=payload.mode,
            promptSummary=prompt_summary,
            sessionId=None,
            intent="ALERT_EXPLANATION",
            recommendations=[],
            engine=engine,
        )


explanation_service = ExplanationService()
