app.cors.allowed-origins=https://ntwebcozumleri.com.tr,https://www.ntwebcozumleri.com.tr,http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001
app.frontend.base-url=https://ntwebcozumleri.com.tr/ecommerce-platform
app.backend.public-url=https://ntwebcozumleri.com.tr/ecommerce-platform
