services:
  postgres:
    mem_limit: 512m

  redis:
    mem_limit: 128m

  api:
    mem_limit: 512m

  worker:
    mem_limit: 768m
    command: celery -A app.celery_app worker --loglevel=INFO --concurrency=1

  scheduler:
    mem_limit: 256m

  web:
    mem_limit: 256m
